# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

matrix:
  include:
    - r: 3.1
      warnings_are_errors: false
    - r: oldrel
    - r: release
      after_success:
        - Rscript -e 'covr::codecov()'
      env: R_CODECOV=true
    - r: devel
